language: ruby
rvm:
  - "2.3.1"
before_script:
  - "mysql -e 'create database travis_test;'"
  - "cp ./config/database.yml.travis ./config/database.yml"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
notifications:
  email:
    on_success: change
    on_failure: change
