require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Members::LinksController do

  # This should return the minimal set of attributes required to create a valid
  # Members::Link. As you add validations to Members::Link, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all members_links as @members_links" do
      link = Members::Link.create! valid_attributes
      get :index
      assigns(:members_links).should eq([link])
    end
  end

  describe "GET show" do
    it "assigns the requested members_link as @members_link" do
      link = Members::Link.create! valid_attributes
      get :show, :id => link.id.to_s
      assigns(:members_link).should eq(link)
    end
  end

  describe "GET new" do
    it "assigns a new members_link as @members_link" do
      get :new
      assigns(:members_link).should be_a_new(Members::Link)
    end
  end

  describe "GET edit" do
    it "assigns the requested members_link as @members_link" do
      link = Members::Link.create! valid_attributes
      get :edit, :id => link.id.to_s
      assigns(:members_link).should eq(link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Members::Link" do
        expect {
          post :create, :members_link => valid_attributes
        }.to change(Members::Link, :count).by(1)
      end

      it "assigns a newly created members_link as @members_link" do
        post :create, :members_link => valid_attributes
        assigns(:members_link).should be_a(Members::Link)
        assigns(:members_link).should be_persisted
      end

      it "redirects to the created members_link" do
        post :create, :members_link => valid_attributes
        response.should redirect_to(Members::Link.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved members_link as @members_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        Members::Link.any_instance.stub(:save).and_return(false)
        post :create, :members_link => {}
        assigns(:members_link).should be_a_new(Members::Link)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Members::Link.any_instance.stub(:save).and_return(false)
        post :create, :members_link => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested members_link" do
        link = Members::Link.create! valid_attributes
        # Assuming there are no other members_links in the database, this
        # specifies that the Members::Link created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Members::Link.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => link.id, :members_link => {'these' => 'params'}
      end

      it "assigns the requested members_link as @members_link" do
        link = Members::Link.create! valid_attributes
        put :update, :id => link.id, :members_link => valid_attributes
        assigns(:members_link).should eq(link)
      end

      it "redirects to the members_link" do
        link = Members::Link.create! valid_attributes
        put :update, :id => link.id, :members_link => valid_attributes
        response.should redirect_to(link)
      end
    end

    describe "with invalid params" do
      it "assigns the members_link as @members_link" do
        link = Members::Link.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Members::Link.any_instance.stub(:save).and_return(false)
        put :update, :id => link.id.to_s, :members_link => {}
        assigns(:members_link).should eq(link)
      end

      it "re-renders the 'edit' template" do
        link = Members::Link.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Members::Link.any_instance.stub(:save).and_return(false)
        put :update, :id => link.id.to_s, :members_link => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested members_link" do
      link = Members::Link.create! valid_attributes
      expect {
        delete :destroy, :id => link.id.to_s
      }.to change(Members::Link, :count).by(-1)
    end

    it "redirects to the members_links list" do
      link = Members::Link.create! valid_attributes
      delete :destroy, :id => link.id.to_s
      response.should redirect_to(members_links_url)
    end
  end

end
